### ISSUE TITLE
Role Assignment

### ISSUE THREAD

**Issue by ZottelvonUrvieh** [petrspelos/Community-Discord-BOT#40]
Add roles to users when they say a specific phrase.

**Additionally:**
* Admins can set the list of phrases
* Admins can set the list of roles to be set
* Admins can establish relations (meaning which phrases "trigger" which roles)

* One role can be invoked by multiple phrases
* One phrase can get you multiple roles

**Comment by petrspelos** [comment]
Implemented in ae9b8ee72faa93c6153f2d630d7740625e7e3986
