### ISSUE TITLE
Purge command not very efficient

### ISSUE THREAD

**Issue by Zwolf8** [petrspelos/Community-Discord-BOT#53]
So I made a rough code for the purge command(s),

```cs
var messages = await Context.Channel.GetMessagesAsync(amountOfMessagesToDelete + 1).FlattenAsync();  // Gets the messages, adds one message to the amount of messages to delete to delete the user's command then flattens it async.

foreach(IMessage msg in messages) // Loops through the index of the collection we made above.
{
    await Task.Delay(600); // Delay so it doesn't reach rate limit.`
    await msg.DeleteAsync(); // Deletes the message
}
```

Basically this works fine, but a solution to delete them in 1 go would be ideal because this has some problems with discord's rate limit and will cause performance issues.

**Comment by petrspelos** [comment]
I'm not the biggest fan of the `Task.Delay`. :thinking: 

I was almost sure there is a method for deleting multiple messages at once.
I'll take a look into it today. :blush: :+1:

**Comment by Zwolf8** [comment]
This is really old by now, it looks like they updated discord.net and discord.net 2.0 now has deletemessagesasync
